import pytest

from devlegate.agent_protocol import (
    AgentProtocolError,
    RenderContext,
    initialize_project,
    render_project,
)


def context() -> RenderContext:
    return RenderContext(
        "automation/state",
        "workflow/waiting",
        "workflow/ready",
        "workflow/inspection",
        "workflow/accepted",
        "develop",
    )


def test_init_seeds_templates_and_generated_skills(tmp_path):
    assert initialize_project(tmp_path, context()) == (2, 2)
    assert (tmp_path / ".devlegate/templates/skills/architect/SKILL.md.tmpl").is_file()
    assert (tmp_path / ".devlegate/templates/skills/reviewer/SKILL.md.tmpl").is_file()
    architect = tmp_path / ".devlegate/generated/skills/architect/SKILL.md"
    reviewer = tmp_path / ".devlegate/generated/skills/reviewer/SKILL.md"
    assert "GENERATED BY DEVLEGATE" in architect.read_text()
    assert "automation/state" in architect.read_text()
    assert "workflow/inspection" in reviewer.read_text()
    assert "devlegate/control" not in reviewer.read_text()
    assert "`main`" not in reviewer.read_text()


def test_init_does_not_overwrite_custom_templates(tmp_path):
    initialize_project(tmp_path, context())
    template = tmp_path / ".devlegate/templates/skills/architect/SKILL.md.tmpl"
    template.write_text(template.read_text() + "\nCUSTOM PROJECT RULE\n")

    assert initialize_project(tmp_path, context()) == (2, 1)
    assert "CUSTOM PROJECT RULE" in (
        tmp_path / ".devlegate/generated/skills/architect/SKILL.md"
    ).read_text()


def test_render_is_deterministic_and_check_is_read_only(tmp_path):
    initialize_project(tmp_path, context())
    generated = tmp_path / ".devlegate/generated/skills/reviewer/SKILL.md"
    before = generated.read_bytes()
    assert render_project(tmp_path, context()) == (2, 0)
    assert generated.read_bytes() == before
    assert render_project(tmp_path, context(), check=True) == (2, 0)
    template = tmp_path / ".devlegate/templates/skills/reviewer/SKILL.md.tmpl"
    template.write_text(template.read_text() + "\nchanged\n")
    with pytest.raises(AgentProtocolError, match="stale"):
        render_project(tmp_path, context(), check=True)
    assert generated.read_bytes() == before


@pytest.mark.parametrize("template_text", ["{{ UNKNOWN }}", "{{ workflow.todo_path"])
def test_unknown_and_malformed_variables_fail_closed(tmp_path, template_text):
    initialize_project(tmp_path, context())
    template = tmp_path / ".devlegate/templates/skills/architect/SKILL.md.tmpl"
    template.write_text(template_text)

    with pytest.raises(AgentProtocolError):
        render_project(tmp_path, context())


def test_render_rejects_symlinked_protocol_root(tmp_path):
    real = tmp_path / "real"
    real.mkdir()
    (tmp_path / ".devlegate").symlink_to(real, target_is_directory=True)

    with pytest.raises(AgentProtocolError, match="symlinked"):
        initialize_project(tmp_path, context())


def test_render_rejects_symlinked_template_leaf(tmp_path):
    initialize_project(tmp_path, context())
    source = tmp_path / ".devlegate/templates/skills/architect/SKILL.md.tmpl"
    target = tmp_path / "outside.tmpl"
    target.write_text("outside\n")
    source.unlink()
    source.symlink_to(target)

    with pytest.raises(AgentProtocolError, match="template path"):
        render_project(tmp_path, context())
