"""Deterministic rendering of project-local Architect and Reviewer skills."""

from __future__ import annotations

import os
import re
import tempfile
from dataclasses import dataclass
from pathlib import Path


class AgentProtocolError(ValueError):
    """Raised when agent protocol templates or paths are invalid."""


@dataclass(frozen=True)
class RenderContext:
    control_branch: str
    backlog_path: str
    todo_path: str
    review_path: str
    done_path: str
    product_branch: str
    execution_branch_prefix: str = "devlegate/work/"

    def values(self) -> dict[str, str]:
        return {
            "workflow.control_branch": self.control_branch,
            "workflow.backlog_path": self.backlog_path,
            "workflow.todo_path": self.todo_path,
            "workflow.review_path": self.review_path,
            "workflow.done_path": self.done_path,
            "product.branch": self.product_branch,
            "execution.branch_prefix": self.execution_branch_prefix,
        }


_PLACEHOLDER = re.compile(r"\{\{(.*?)\}\}", re.DOTALL)
_TEMPLATE_FILES = (
    Path("skills/architect/SKILL.md.tmpl"),
    Path("skills/reviewer/SKILL.md.tmpl"),
)
_MARKER = (
    "<!--\nGENERATED BY DEVLEGATE.\nSource: {source}\n"
    "Do not edit this file directly.\n-->\n\n"
)


def packaged_template_root() -> Path:
    """Return the read-only packaged bootstrap template directory."""
    return Path(__file__).parent / "default_templates"


def _directory(path: Path, label: str, *, create: bool = True) -> None:
    if path.is_symlink():
        raise AgentProtocolError(f"unsafe symlinked {label}: {path}")
    if path.exists() and not path.is_dir():
        raise AgentProtocolError(f"{label} is not a directory: {path}")
    if create:
        path.mkdir(parents=True, exist_ok=True)
    elif not path.is_dir():
        raise AgentProtocolError(f"{label} is missing: {path}")


def _safe_project_roots(
    project: Path, *, create: bool = True
) -> tuple[Path, Path, Path]:
    protocol = project / ".devlegate"
    templates = protocol / "templates"
    generated = protocol / "generated"
    _directory(protocol, ".devlegate root", create=create)
    _directory(templates, "template root", create=create)
    _directory(generated, "generated root", create=create)
    return protocol, templates, generated


def _render_template(template: str, context: RenderContext, source: Path) -> str:
    values = context.values()

    if template.count("{{") != template.count("}}"):
        raise AgentProtocolError(f"malformed placeholder in template: {source}")

    def replace(match: re.Match[str]) -> str:
        name = match.group(1).strip()
        if not re.fullmatch(r"[a-z]+\.[a-z_]+", name):
            raise AgentProtocolError(
                f"malformed or unknown variable {name!r} in {source}"
            )
        if name not in values:
            raise AgentProtocolError(f"unknown render variable {name!r} in {source}")
        return values[name]

    rendered = _PLACEHOLDER.sub(replace, template)
    if "{{" in rendered or "}}" in rendered:
        raise AgentProtocolError(f"malformed placeholder in template: {source}")
    return rendered.rstrip("\r\n") + "\n"


def _output_path(generated: Path, template_relative: Path) -> Path:
    if template_relative.suffix != ".tmpl":
        raise AgentProtocolError(f"unsupported template path: {template_relative}")
    output = generated / template_relative.with_suffix("")
    if output.parent != generated / template_relative.parent:
        raise AgentProtocolError(f"ambiguous generated path: {template_relative}")
    return output


def _atomic_write(path: Path, content: str) -> bool:
    if path.is_symlink():
        raise AgentProtocolError(f"unsafe symlinked generated file: {path}")
    if path.exists() and not path.is_file():
        raise AgentProtocolError(f"generated path is not a file: {path}")
    if path.is_file() and path.read_text() == content:
        return False
    temporary_name = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            dir=path.parent,
            prefix=f".{path.name}.",
            suffix=".tmp",
            delete=False,
        ) as temporary:
            temporary_name = temporary.name
            temporary.write(content)
            temporary.flush()
            os.fsync(temporary.fileno())
        os.replace(temporary_name, path)
        directory_fd = os.open(path.parent, os.O_RDONLY)
        try:
            os.fsync(directory_fd)
        finally:
            os.close(directory_fd)
    except OSError as error:
        raise AgentProtocolError(
            f"cannot write generated file {path}: {error}"
        ) from error
    finally:
        if temporary_name is not None:
            try:
                os.unlink(temporary_name)
            except FileNotFoundError:
                pass
    return True


def initialize_project(project: Path, context: RenderContext) -> tuple[int, int]:
    """Seed missing project templates and render generated skills."""
    _protocol, templates, generated = _safe_project_roots(project)
    _directory(templates / "skills", "skills template directory")
    _directory(templates / "prompts", "prompts template directory")
    _directory(generated / "skills", "skills generated directory")
    for relative in _TEMPLATE_FILES:
        source = templates / relative
        if source.is_symlink() or source.parent.is_symlink():
            raise AgentProtocolError(f"unsafe symlinked template file: {source}")
        if source.exists():
            if not source.is_file():
                raise AgentProtocolError(f"template path is not a file: {source}")
            continue
        packaged = packaged_template_root() / relative
        if not packaged.is_file():
            raise AgentProtocolError(f"packaged template is missing: {packaged}")
        source.parent.mkdir(parents=True, exist_ok=True)
        source.write_bytes(packaged.read_bytes())
    return render_project(project, context)


def render_project(
    project: Path, context: RenderContext, *, check: bool = False
) -> tuple[int, int]:
    """Render project-owned templates, or check generated output without writing."""
    _protocol, templates, generated = _safe_project_roots(project, create=not check)
    _directory(templates / "skills", "skills template directory", create=not check)
    _directory(templates / "prompts", "prompts template directory", create=not check)
    _directory(generated / "skills", "skills generated directory", create=not check)
    changed = 0
    for relative in _TEMPLATE_FILES:
        source = templates / relative
        if (
            source.is_symlink()
            or source.parent.is_symlink()
            or not source.is_file()
        ):
            raise AgentProtocolError(f"template path is unavailable: {source}")
        output = _output_path(generated, relative)
        if output.parent.is_symlink():
            raise AgentProtocolError(
                f"unsafe symlinked generated directory: {output.parent}"
            )
        if not check:
            _directory(output.parent, "generated skill directory")
        rendered = _render_template(source.read_text(), context, source)
        marker = _MARKER.format(source=f".devlegate/templates/{relative}")
        expected = marker + rendered
        if check:
            if (
                output.is_symlink()
                or not output.is_file()
                or output.read_text() != expected
            ):
                raise AgentProtocolError(
                    f"stale or missing generated artifact: {output}"
                )
        elif _atomic_write(output, expected):
            changed += 1
    return len(_TEMPLATE_FILES), changed


__all__ = [
    "AgentProtocolError",
    "RenderContext",
    "initialize_project",
    "packaged_template_root",
    "render_project",
]
